# workflow的名字
name: deploy

# 當以下事件發生時，觸發
on:
  # 這邊設定的是：push/pullrequest 到 main 時即觸發
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # 有加這行可以手動觸發 actions
  workflow_dispatch:

# 觸發內容
jobs:
  # 這個workflow有個job叫做build
  build:
    # 這個job要run在ubuntu上
    runs-on: ubuntu-latest

    # job的步驟要做些什麼咧
    steps:
      # 1. 專門for node.js的actions，記得依node.js版本更新其後version
      - uses: actions/checkout@v4
      # 把內容 build 起來
      - name: Install & Build # 執行
        run: |
          npm install
          npm run build

      # 2. deploy
      - name: Deploy
        # 別人的actions拿來借用
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }} # Settings > Secret 建立的 ACCESS_TOKEN，推同個 repo 的話可以不需要
          BRANCH: gh-action # deploy 到 gh-pages 這個分支
          FOLDER: dist # build 後的資料夾
